onlineshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("shop.urls")),
    path("products/", include("products.urls")),
    path("shopping_bag/", include("shopping_bag.urls")),
    path("checkout/", include("checkout.urls")),
    path("profile/", include("profiles.urls")),
    path("reviews/", include("reviews.urls")),
    path("loyalty/", include("loyalty.urls")),
    path("contact/", include("contact.urls")),
    path("newsletter/", include("newsletter.urls")),
    path('privacy_policy/', include('privacy_policy.urls')),
]
# serving media files
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

# Serving static files
if not settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

handler404 = "onlineshop.views.handler404"

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

shopping_bag/urls.py
from django.urls import path
from . import views

app_name = "shopping_bag"

urlpatterns = [
    path("", views.view_shopping_bag, name="view_shopping_bag"),
    path(
        "add/<item_id>/", views.add_to_shopping_bag, name="add_to_shopping_bag"
    ),
    path(
        "adjust/<item_id>/",
        views.adjust_shopping_bag,
        name="adjust_shopping_bag",
    ),
    path(
        "remove/<int:item_id>/",
        views.remove_from_shopping_bag,
        name="remove_from_shopping_bag",
    ),
]

shopping_bag/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.http import JsonResponse
from products.models import Products


def view_shopping_bag(request):
    """
    A view to display the shopping bag
    """

    bag = request.session.get("bag", {})
    loyalty_points = None

    if request.user.is_authenticated:
        from loyalty.models import LoyaltyPoints

        try:
            loyalty_points = LoyaltyPoints.objects.get(user=request.user)
        except LoyaltyPoints.DoesNotExist:
            loyalty_points = LoyaltyPoints.objects.create(
                user=request.user, points=0
            )

    context = {
        "bag": bag,
        "loyalty_points": (
            loyalty_points.points if loyalty_points else 0
        ),  # Pass only the points
    }
    return render(request, "shopping_bag/shopping_bag.html")


def add_to_shopping_bag(request, item_id):
    """
    Add a product quantity to the shopping bag.
    Supports items with or without sizes.
    """
    product = get_object_or_404(Products, pk=item_id)
    quantity = int(request.POST.get("quantity", 1))
    redirect_url = request.POST.get("redirect_url")
    size = request.POST.get("product_size")
    bag = request.session.get("bag", {})

    if size:
        if str(item_id) in bag:
            if size in bag[str(item_id)].get("items_by_size", {}):
                bag[str(item_id)]["items_by_size"][size] += quantity
                messages.success(
                    request,
                    f'Updated size {size.upper()} {product.name} quantity to '
                    f'{bag[str(item_id)]["items_by_size"][size]}'
                )
            else:
                bag[str(item_id)]["items_by_size"][size] = quantity
                messages.success(
                    request,
                    f"Added size {size.upper()} {product.name} "
                    "to your shopping bag"
                )
        else:
            bag[str(item_id)] = {"items_by_size": {size: quantity}}
            messages.success(
                request,
                f"Added size {size.upper()} {product.name} "
                "to your shopping bag",
            )
    else:
        if str(item_id) in bag:
            bag[str(item_id)] += quantity
            messages.success(
                request,
                f"Updated {product.name} quantity to {bag[str(item_id)]}",
            )
        else:
            bag[str(item_id)] = quantity
            messages.success(
                request, f"Added {product.name} to your shopping bag"
            )

    request.session["bag"] = bag
    return redirect(redirect_url)


def adjust_shopping_bag(request, item_id):
    """
    Adjust the quantity of the product in the shopping bag
    """
    product = get_object_or_404(Products, pk=item_id)
    quantity = int(request.POST.get("quantity", 1))
    size = request.POST.get("product_size", None)
    bag = request.session.get("bag", {})

    if size:
        if str(item_id) in bag and "items_by_size" in bag[str(item_id)]:
            if quantity > 0:
                bag[str(item_id)]["items_by_size"][size] = quantity
                messages.success(
                    request,
                    f'Updated size {size.upper()} {product.name} quantity to '
                    f'{bag[str(item_id)]["items_by_size"][size]}'
                )
            else:
                del bag[str(item_id)]["items_by_size"][size]
                if not bag[str(item_id)]["items_by_size"]:
                    bag.pop(str(item_id))
                messages.success(
                    request,
                    f"Removed size {size.upper()} {product.name} "
                    "from your shopping bag",
                )
        else:
            messages.error(request, "Item or size not found in bag.")
    else:
        if quantity > 0:
            bag[str(item_id)] = quantity
            messages.success(
                request,
                f"Updated {product.name} quantity to {bag[str(item_id)]}",
            )
        else:
            bag.pop(str(item_id))
            messages.success(
                request, f"Removed {product.name} from the shopping bag."
            )

    request.session["bag"] = bag
    return redirect("shopping_bag:view_shopping_bag")


def remove_from_shopping_bag(request, item_id):
    product = get_object_or_404(Products, pk=item_id)
    try:
        bag = request.session.get("bag", {})
        if str(item_id) in bag:
            del bag[str(item_id)]
            request.session["bag"] = bag
            messages.success(
                request, f"Removed {product.name} from your shopping bag."
            )
            return JsonResponse({"status": "success"}, status=200)
        else:
            return JsonResponse(
                {"error": "Item not found in the bag"}, status=400
            )
    except Exception as e:
        return JsonResponse({"error": str(e)}, status=500)

shopping_bag/templates/shopping_bag/bag-total.html
<h6><strong>Bag Total: Euro {{ total|floatformat:2 }}</strong></h6>
<h6>Delivery: Euro {{ delivery|floatformat:2 }}</h6>
{% if points_applied %}
<p>Loyalty Points Applied: €{{ points_applied|floatformat:2 }}</p>
{% endif %}
<h4 class="mt-4"><strong>Grand Total: Euro {{ grand_total|floatformat:2 }}</strong></h4>
{% if free_delivery_delta > 0 %}
<p class="mb-1 text-danger">
    You could get free delivery by spending just <strong>{{ free_delivery_delta|floatformat:2 }}</strong> more!
</p>
{% endif %}

shopping_bag/templates/shopping_bag/checkout-buttons.html
{% if loyalty_points %}
<div class="loyalty-points-section text-right mb-4">
    <p>You have <strong>{{ loyalty_points }}</strong> loyalty points available.</p>
    <p>These points are worth: <strong>€{{ loyalty_points|floatformat:2 }}</strong></p>
    <!-- Warning Message -->
    <div class="alert alert-warning" role="alert">
        <strong>Important:</strong> If you apply your loyalty points but do not complete the order, the points will be lost, as session details are deleted for security reasons.
    </div>
    <form method="POST" action="{% url 'apply_loyalty_points' %}">
        {% csrf_token %}
        <input type="hidden" name="points" value="{{ loyalty_points }}">
        <button type="submit" class="btn custom-edit-btn rounded-0 btn-sm w-10 my-2">Apply Loyalty Points</button>
    </form>
</div>
{% else %}
<div class="text-right mb-4">
    <p>No loyalty points available.</p>
</div>
{% endif %}

<div class="d-flex justify-content-end mt-4">
    <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0 btn-sm mr-2">
        <span class="icon">
            <i class="fas fa-chevron-left"></i>
        </span>
        <span class="text-uppercase">Keep Shopping</span>
    </a>
    <a href="{% url 'checkout' %}" class="btn custom-edit-btn rounded-0 btn-sm">
        <span class="text-uppercase">Secure Checkout</span>
        <span class="icon">
            <i class="fas fa-lock"></i>
        </span>
    </a>
</div>

shopping_bag/templates/shopping_bag/product-image.html
{% if item.product.image %}
<img class="shopping-bag-img img-fluid rounded" src="{{ item.product.image.url }}" alt="{{ item.product.name }}">
{% else %}
<img class="img-fluid rounded" src="{{ MEDIA_URL }}noimage.png" alt="{{ item.product.name }}">
{% endif %}

shopping_bag/templates/shopping_bag/product-info.html
<p class="my-0"><strong>{{ item.product.name }}</strong></p>
<p class="my-0"><strong>Size:</strong> {% if item.size %}{{ item.size|upper }}{% else %}N/A{% endif %}</p>
<p class="my-0 small text-muted">SKU: {{ item.product.sku|upper }}</p>

shopping_bag/templates/shopping_bag/quantity-form.html
<form class="form update-form" method="POST" action="{% url 'shopping_bag:adjust_shopping_bag' item.item_id %}">
    {% csrf_token %}
    <div class="form-group">
        <div class="input-group input-gropu-{{ item.item_id }}">
            <div class="input-group-prepend">
                <button class="decrement-qty btn btn-sm btn-black rounded-0 decrement-qty_{{ item.item_id }} 
                    {% if item.size %}decrement-size_{{ item.item_id }}_{{ item.size }}{% endif %}" 
                    data-item_id="{{ item.item_id }}" data-size="{{ item.size }}">
                    <span>
                        <i class="fas fa-minus fa-sm"></i>
                    </span>                                           
                </button>
            </div>
            <input class="form-control form-control-sm qty_input id_qty_{{ item.item_id }} 
                {% if item.size %}size_{{ item.item_id }}_{{ item.size }}{% endif %}" type="number"
                name="quantity" value="{{ item.quantity }}" min="1" max="99"
                data-item_id="{{ item.item_id }}" data-size="{{ item.size }}">
                <div class="input-group-append">
                    <button class="increment-qty btn btn-sm btn-black rounded-0 increment-qty_{{ item.item_id }} 
                    {% if item.size %}increment-size_{{ item.item_id }}_{{ item.size }}{% endif %}"
                    data-item_id="{{ item.item_id }}" data-size="{{ item.size }}">
                        <span>
                            <i class="fas fa-plus fa-sm"></i>
                        </span>                                           
                    </button>                                           
                </div>
                {% if item.product.has_sizes %}
                <input type="hidden" name="product_size" value="{{ item.size }}">
                {% endif %}
        </div>
    </div>
</form>
<a class="update-link text-info">Update</a>
<a class="remove-item text-danger float-right" id="remove_{{ item.item_id }}" data-product_size="{{ item.size }}"><small>Remove</small></a>

shopping_bag/templates/shopping_bag/shopping_bag.html
{% extends "base.html" %}
{% load static %}
{% load bag_tools %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container mb-2">
    <div class="row">
        <div class="col">
            <hr>
            <h2 class="logo-font mb-4">Shopping Bag</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            {% if shopping_bag_items %}
            <div class="d-block d-md-none"> 
                <div class="row">
                    <div class="col">
                        {% include 'shopping_bag/bag-total.html' %}
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        {% include 'shopping_bag/checkout-buttons.html' %}
                        <p class="text-muted mb-5">Summary of shopping bag contents below</p>
                    </div>
                </div>
                {% for item in shopping_bag_items %}
                <div class="row">
                    <div class="col-12 col-sm-6 mb-2">
                        {% include "shopping_bag/product-image.html" %}
                    </div>
                    <div class="col-12 col-sm-6 mb-2">
                        {% include "shopping_bag/product-info.html" %}
                    </div>
                    <div class="col-12 col-sm-6 order-sm-last">
                        <p class="my-0">Price Each: ${{ item.product.price }}</p>
                        <p><strong>Subtotal: </strong>${{ item.product.price | calc_subtotal:item.quantity }}</p>
                    </div>
                    <div class="col-12 col-sm-6">
                        {% include "shopping_bag/quantity-form.html" %}
                    </div>
                </div>
                <div class="row"><div class="col"><hr></div></div>
            {% endfor %}
            <div class="btt-button shadow-sm rounded-0 border border-black">
                <a class="btt-link d-flex h-100">
                    <i class="fas fa-arrow-up text-black mx-auto my-auto"></i>
                </a>	
            </div>      

            </div>
            <div class="table-responsive rounded d-none d-md-block ">
                
                <table class="table table-sm table-borderless">
                    <thead class="text-black">
                        <tr>
                            <th scope="col">Product Info</th>
                            <th></th>
                            <th scope="col">Price</th>
                            <th scope="col">Qty</th>
                            <th scope="col">Subtotal</th>
                        </tr>
                    </thead>

                    {% for item in shopping_bag_items %}
                    <tr>
                        <td class="py-3 w-25">
                            {% include 'shopping_bag/product-image.html' %}
                        </td>
                        <td class="py-3">
                            {% include 'shopping_bag/product-info.html' %}
                        </td>
                        <td class="py-3">
                            <p class="my-0">Euro {{ item.product.price|floatformat:2 }}</p>
                        </td>
                        <td class="py-3 w-25">
                            {% include 'shopping_bag/quantity-form.html' %}
                        </td>
                        <td class="py-3">
                            <p class="my-0">Euro {{ item.product.price | calc_subtotal:item.quantity }}</p>
                            
                        </td>
                    </tr>
                    {% endfor %}
                    
                    <!-- total cost -->
                    <tr>
                        <td colspan="5" class="pt-5 text-right">
                            {% include 'shopping_bag/bag-total.html' %}
                        </td>
                    </tr>
                    <tr>
                        <td colspan="5" class="text-right">
                            {% include 'shopping_bag/checkout-buttons.html' %}
                        </td>
                    </tr>
                </table>
                {% else %}
                <p class="lead mb-5">Your Shopping Bag is empty</p>
                <a href="{% url 'products' %}" class="btn btn-black rounded-0 btn-lg">
                    <span class="icon">
                        <i class="fas fa-chevron-left"></i>
                    </span>
                    <span class="text-uppercase">Keep Shopping</span>
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}

    <script>
        $(document).ready(function() {
            $('.btt-link').click(function(e) {
                e.preventDefault(); 
                $('html, body').animate({ scrollTop: 0 }, 'slow'); 
            });
        });
    </script>
    <script src="{% static 'js/quantity_input_script.js' %}"></script>
    <script src="{% static 'js/shopping_bag_script.js' %}"></script>
    <script>
        
    
        // Remove item and reload on click
        $('.remove-item').click(function(e) {
            var csrfToken = '{{ csrf_token }}';
            var itemId = $(this).attr('id').split('remove_')[1];
            var size = $(this).data('product_size');
            var url = `/shopping_bag/remove/${itemId}/`;
            var data = {'csrfmiddlewaretoken': csrfToken, 'product_size': size }

            $.post(url, data)
            .done(function() {
                location.reload();
    })
})
    </script>
{% endblock %}