onlineshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("shop.urls")),
    path("products/", include("products.urls")),
    path("shopping_bag/", include("shopping_bag.urls")),
    path("checkout/", include("checkout.urls")),
    path("profile/", include("profiles.urls")),
    path("reviews/", include("reviews.urls")),
    path("loyalty/", include("loyalty.urls")),
    path("contact/", include("contact.urls")),
    path("newsletter/", include("newsletter.urls")),
    path('privacy_policy/', include('privacy_policy.urls')),
]
# serving media files
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

# Serving static files
if not settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

handler404 = "onlineshop.views.handler404"

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

shopping_bag/urls.py
from django.urls import path
from . import views

app_name = "shopping_bag"

urlpatterns = [
    path("", views.view_shopping_bag, name="view_shopping_bag"),
    path(
        "add/<item_id>/", views.add_to_shopping_bag, name="add_to_shopping_bag"
    ),
    path(
        "adjust/<item_id>/",
        views.adjust_shopping_bag,
        name="adjust_shopping_bag",
    ),
    path(
        "remove/<int:item_id>/",
        views.remove_from_shopping_bag,
        name="remove_from_shopping_bag",
    ),
]

templates/includes/toasts/toast_error.html
<div class="toast custom-toast rounded-0 border-top-0" data-autohide="false">
    <div class="arrow-up arrow-danger"></div>
    <div class="w-100 toast-capper bg-danger"></div>
    <div class="toast-header bg-white text-dark">
        <strong class="mr-auto">Danger!</strong>
        <button type="button" class="ml-2 mb-1 close text-dark" data-dismiss="toast" area-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="toast-body bg-white">
        {{ message }}
    </div>
</div>

templates/includes/toasts/toast_info.html
<div class="toast custom-toast rounded-0 border-top-0" data-autohide="false">
    <div class="arrow-up arrow-info"></div>
    <div class="w-100 toast-capper bg-info"></div>
    <div class="toast-header bg-white text-dark">
        <strong class="mr-auto">Alert!</strong>
        <button type="button" class="ml-2 mb-1 close text-dark" data-dismiss="toast" area-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="toast-body bg-white">
        {{ message }}
    </div>
</div>

templates/includes/toasts/toast_loyalty_success.html
<div class="toast custom-toast rounded-0 border-top-0" data-autohide="false">
    <div class="arrow-up arrow-success"></div>
    <div class="w-100 toast-capper bg-success"></div>
    <div class="toast-header bg-white text-dark">
        <strong class="mr-auto">Success!</strong>
        <button type="button" class="ml-2 mb-1 close text-dark" data-dismiss="toast">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="toast-body bg-white">
        <div class="row">
            <div class="col">
                {{ message }}
            </div>
        </div>
        <!-- No bag details or checkout link for loyalty points  as was confusing the user -->
    </div>
</div>

templates/includes/toasts/toast_order_success.html
<div class="toast custom-toast rounded-0 border-top-0" data-autohide="false">
    <div class="arrow-up arrow-success"></div>
    <div class="w-100 toast-capper bg-success"></div>
    <div class="toast-header bg-white text-dark">
        <strong class="mr-auto">Success!</strong>
        <button type="button" class="ml-2 mb-1 close text-dark" data-dismiss="toast">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="toast-body bg-white">
        <div class="row">
            <div class="col">
                {{ message }}
                <hr class="mt-1 mb-3">
            </div>
        </div>
        <!-- Removed the bag details block -->
        <div class="row">
            <div class="col">
                <p class="mt-3 mb-1 text-black">
                    <strong>Order Total: <span class="float-right">€{{ grand_total|floatformat:2 }}</span></strong>
                </p>
                <p class="mt-1 text-black">
                    Order Number: <strong>{{ order.order_number }}</strong>
                </p>
                <!-- Add any other order-specific details as needed -->
            </div>
        </div>
    </div>
</div>

templates/includes/toasts/toast_success.html
<div class="toast custom-toast rounded-0 border-top-0" data-autohide="false">
    <div class="arrow-up arrow-success"></div>
    <div class="w-100 toast-capper bg-success"></div>
    <div class="toast-header bg-white text-dark">
        <strong class="mr-auto">Success!</strong>
        <button type="button" class="ml-2 mb-1 close text-dark" data-dismiss="toast">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="toast-body bg-white">
        <div class="row">
            <div class="col">
                {{ message }}
                <hr class="mt-1 mb-3">
            </div>
        </div>
        {% if grand_total and not on_profile_page %}
        <p class="logo-font bg-white text-black py-1">Your Bag ({{ product_count }})</p>
        <div class="bag-notification-wrapper">
            {% for item in shopping_bag_items %}
                <div class="row">
                    <div class="col-3 my-1">
                        {% if item.product.image %}
                        <img class="w-100" src="{{ item.product.image.url }}" alt="{{ item.product.name}}">
                        {% else %}
                        <img class="w-100" src="{{ MEDIA_URL }}noimage.png" alt="{{ item.product.name}}">
                        {% endif %}
                    </div>
                    <div class="col-9">
                        <p class="my-0"><strong>{{ item.product.name }}</strong></p>
                        <p class="my-0 small">Size: {% if item.product.has_sizes %}{{ item.size|upper }}{% else %}N/A{% endif %}</p>
                        <p class="my-0 small text-muted">Qty: {{ item.quantity }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col">
                <p class="mt-3 mb-1 text-black">
                    <strong>Total{% if free_delivery_delta > 0 %} (Exc. delivery){% endif %}: 
                    <span class="float-right">€{{ grand_total|floatformat:2 }}</span></strong>
                </p>
                {% if free_delivery_delta > 0 %}
                    <p class="mb-0 p-2 bg-warning shadow-sm text-black text-center">
                        Spend <strong>€{{ free_delivery_delta }}</strong> more to get free next day delivery!
                    </p>
                {% endif %}
                <a href="{% url 'shopping_bag:view_shopping_bag' %}" class="btn btn-black btn-block rounded-0">
                    <span class="text-uppercase">Go To Secure Checkout</span>
                    <span class="icon">
                        <i class="fas fa-lock"></i>
                    </span>
                </a>
            </div>
        </div>
    {% endif %}
    
    </div>
</div>

templates/includes/toasts/toast_warning.html
<div class="toast custom-toast rounded-0 border-top-0" data-autohide="false">
    <div class="arrow-up arrow-warning"></div>
    <div class="w-100 toast-capper bg-warning"></div>
    <div class="toast-header bg-white text-dark">
        <strong class="mr-auto">Warning!</strong>
        <button type="button" class="ml-2 mb-1 close text-dark" data-dismiss="toast" area-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="toast-body bg-white">
        {{ message }}
    </div>
</div>